### PR TITLE
fix: support Parallel V1 search and extract

### LINKED ISSUE #8283: [Bug] ParallelTools search/extract fail with parallel-web >=1.0.0 due to beta endpoint usage
### Description

Agno's `ParallelTools` currently calls Parallel Search/Extract through the beta SDK namespace:

- `self.parallel_client.beta.search(**search_params)`
- `self.parallel_client.beta.extract(**extract_params)`

With `parallel-web` 1.0.x, Parallel moved Search and Extract to GA/V1 methods:

- `client.search(...)`
- `client.extract(...)`

As a result, Agno's Parallel search/extract tooling fails with the latest Parallel SDK because `client.beta` no longer exposes `search`/`extract`.

This appears to affect `libs/agno/agno/tools/parallel.py`, and the current unit tests also mock `parallel_client.beta.search` / `parallel_client.beta.extract`, so they do not catch the SDK 1.0.x behavior.

### Steps to Reproduce

1. Install Agno and Parallel SDK:

   ```bash
   pip install agno==2.6.11 parallel-web==1.0.0
   ```

2. Set `PARALLEL_API_KEY`.

3. Run:

   ```python
   from agno.tools.parallel import ParallelTools

   tools = ParallelTools()
   print(
       tools.parallel_search(
           objective="Find latest information about Parallel Web Systems",
           search_queries=["Parallel Web Systems latest product releases"],
       )
   )
   ```

4. Observe that Agno calls `self.parallel_client.beta.search(...)`.

### Agent Configuration (if applicable)

```python
from agno.tools.parallel import ParallelTools

tools = ParallelTools(
    enable_search=True,
    enable_extract=True,
)
```

### Expected Behavior

`ParallelTools.parallel_search()` and `ParallelTools.parallel_extract()` should work with the current `parallel-web` 1.0.x SDK by using the GA/V1 SDK methods and request shapes.

### Actual Behavior

Search fails with an error like:

```text
'BetaResource' object has no attribute 'search'
```

`parallel_extract` appears to be affected by the same issue because Agno also calls the old beta SDK path:

```python
self.parallel_client.beta.extract(**extract_params)
```

So Search and Extract currently depend on Parallel's beta SDK namespace, while `parallel-web` 1.0.x expects the GA/V1 methods such as `client.search(...)` and `client.extract(...)`.

### Screenshots or Logs (if applicable)

_No response_

### Environment

- OS: Ubuntu Linux
- Agno Version: 2.6.11
- External Dependency Versions:
  - parallel-web: 1.0.0
- Additional Environment Details:
  - Python: 3.x
  - `PARALLEL_API_KEY` set

### Possible Solutions (optional)

Update `ParallelTools` to use Parallel's GA/V1 SDK methods:

- `self.parallel_client.search(**search_params)`
- `self.parallel_client.extract(**extract_params)`

The migration may also need request-parameter updates, not only removing `.beta`:

- Search V1 requires `search_queries`; settings like `max_results`, `source_policy`, `fetch_policy`, and excerpt settings now belong under `advanced_settings`.
- Extract V1 uses `client.extract(...)`; fetch/excerpt/full-content settings are also reorganized under `advanced_settings`.

Tests should be updated to mock/assert GA methods instead of `parallel_client.beta.search` and `parallel_client.beta.extract`.

### Additional Context

Parallel has an official Search migration guide for moving from Beta to GA/V1:
https://docs.parallel.ai/search/search-migration-guide

The guide documents the relevant SDK change:

- Beta: `client.beta.search()` using `/v1beta/search`
- GA/V1: `client.search()` using `/v1/search`

It also notes that the V1 request shape changed: `search_queries` is now required, and settings such as `max_results`, `source_policy`, `fetch_policy`, and excerpt settings should be moved under `advanced_settings`.

Agno's current `ParallelTools.parallel_search()` still uses the old beta SDK path and beta-style request shape, so it breaks with `parallel-web` 1.0.x.

### PR DESCRIPTION
**Pull request by fengjikui**
## Summary

Fixes #8283.

Updates `ParallelTools.parallel_search()` and `ParallelTools.parallel_extract()` to work with `parallel-web` 1.0.x, where Search and Extract moved from `client.beta.search()` / `client.beta.extract()` to top-level `client.search()` / `client.extract()`.

The change builds V1 request shapes for the new SDK methods while keeping a beta fallback for older clients:
- Search settings such as `max_results`, excerpt settings, source policy, and fetch policy are nested under `advanced_settings`.
- Objective-only Agno calls still work by using the objective as the V1-required `search_queries` value.
- The old implicit Search mode is preserved by mapping beta `one-shot` semantics to V1 `basic`; explicit `agentic` maps to V1 `advanced`.
- Extract settings such as excerpt size, full content, and fetch policy are nested under `advanced_settings`.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Improvement
- [ ] Model update
- [ ] Other:

---

## Checklist

- [x] Code complies with style guidelines
- [ ] Ran format/validation scripts (`./scripts/format.sh` and `./scripts/validate.sh`)
- [x] Self-review completed
- [x] Documentation updated (comments, docstrings)
- [ ] Examples and guides: Relevant cookbook examples have been included or updated (if applicable)
- [x] Tested in clean environment
- [x] Tests added/updated (if applicable)

### Duplicate and AI-Generated PR Check

- [x] I have searched existing [open pull requests](../../pulls) and confirmed that no other PR already addresses this issue
- [ ] If a similar PR exists, I have explained below why this PR is a better approach
- [x] Check if this PR was entirely AI-generated (by Copilot, Claude Code, Cursor, etc.)

---

## Additional Notes

AI-assisted contribution disclosure: I used Codex to inspect the issue, update the implementation, and run local checks. I reviewed the changed files and validation output before opening this PR.

Duplicate PR checks run before opening:
- `gh pr list --repo agno-agi/agno --state open --search "8283 in:body"` returned `[]`
- `gh pr list --repo agno-agi/agno --state open --search "ParallelTools parallel-web beta endpoint"` returned `[]`

Validation run:
- `PYTHONPATH=libs/agno uvx --with pytest --with pytest-mock --with parallel-web --with pydantic --with pydantic-settings --with python-dotenv --with rich --with typer --with pyyaml --with httpx --with packaging --with docstring-parser --with gitpython --with python-multipart pytest libs/agno/tests/unit/tools/test_parallel_tools.py -q` -> 20 passed
- `uvx ruff format libs/agno/agno/tools/parallel.py libs/agno/tests/unit/tools/test_parallel_tools.py --check` -> 2 files already formatted
- `uvx ruff check libs/agno/agno/tools/parallel.py libs/agno/tests/unit/tools/test_parallel_tools.py` -> all checks passed
- `uvx ruff check libs/agno` -> all checks passed
- `PYTHONPATH=libs/agno uvx --with mypy==1.18.2 --with parallel-web --with pydantic --with pydantic-settings --with python-dotenv --with rich --with typer --with pyyaml --with httpx --with packaging --with docstring-parser --with gitpython --with python-multipart mypy libs/agno/agno/tools/parallel.py --config-file libs/agno/pyproject.toml` -> success
- `git diff --check` -> success
- `uvx --with parallel-web --with socksio python ...` confirmed current `parallel-web` exposes top-level `search` and `extract`, while `beta.search` and `beta.extract` are absent

I did not run the root `./scripts/format.sh` / `./scripts/validate.sh` end-to-end because the full format check reports an unrelated pre-existing formatting change in `libs/agno/agno/models/tuning_engines/tuning_engines.py`. I left unrelated files untouched.

### CODE REVIEW

**Comment by fenil210-cactus** [comment]
Hey @kausmeows can you please check this one ^^ ? fixes important bug wrt https://github.com/agno-agi/agno/issues/8283

**Comment by fengjikui** [comment]
Closing this because it has been superseded by #8453, which was merged and explicitly fixes #8283 by migrating ParallelTools to the GA parallel-web API. Keeping this open would now leave a conflicting duplicate PR. Thanks for the review signal on the original bug.
