### ISSUE TITLE
[Bug] ParallelTools search/extract fail with parallel-web >=1.0.0 due to beta endpoint usage

### ISSUE THREAD

**Issue by fenil210** [agno-agi/agno#8283]
### Description

Agno's `ParallelTools` currently calls Parallel Search/Extract through the beta SDK namespace:

- `self.parallel_client.beta.search(**search_params)`
- `self.parallel_client.beta.extract(**extract_params)`

With `parallel-web` 1.0.x, Parallel moved Search and Extract to GA/V1 methods:

- `client.search(...)`
- `client.extract(...)`

As a result, Agno's Parallel search/extract tooling fails with the latest Parallel SDK because `client.beta` no longer exposes `search`/`extract`.

This appears to affect `libs/agno/agno/tools/parallel.py`, and the current unit tests also mock `parallel_client.beta.search` / `parallel_client.beta.extract`, so they do not catch the SDK 1.0.x behavior.

### Steps to Reproduce

1. Install Agno and Parallel SDK:

   ```bash
   pip install agno==2.6.11 parallel-web==1.0.0
   ```

2. Set `PARALLEL_API_KEY`.

3. Run:

   ```python
   from agno.tools.parallel import ParallelTools

   tools = ParallelTools()
   print(
       tools.parallel_search(
           objective="Find latest information about Parallel Web Systems",
           search_queries=["Parallel Web Systems latest product releases"],
       )
   )
   ```

4. Observe that Agno calls `self.parallel_client.beta.search(...)`.

### Agent Configuration (if applicable)

```python
from agno.tools.parallel import ParallelTools

tools = ParallelTools(
    enable_search=True,
    enable_extract=True,
)
```

### Expected Behavior

`ParallelTools.parallel_search()` and `ParallelTools.parallel_extract()` should work with the current `parallel-web` 1.0.x SDK by using the GA/V1 SDK methods and request shapes.

### Actual Behavior

Search fails with an error like:

```text
'BetaResource' object has no attribute 'search'
```

`parallel_extract` appears to be affected by the same issue because Agno also calls the old beta SDK path:

```python
self.parallel_client.beta.extract(**extract_params)
```

So Search and Extract currently depend on Parallel's beta SDK namespace, while `parallel-web` 1.0.x expects the GA/V1 methods such as `client.search(...)` and `client.extract(...)`.

### Environment

- OS: Ubuntu Linux
- Agno Version: 2.6.11
- External Dependency Versions:
  - parallel-web: 1.0.0
- Additional Environment Details:
  - Python: 3.x
  - `PARALLEL_API_KEY` set

### Possible Solutions (optional)

Update `ParallelTools` to use Parallel's GA/V1 SDK methods:

- `self.parallel_client.search(**search_params)`
- `self.parallel_client.extract(**extract_params)`

The migration may also need request-parameter updates, not only removing `.beta`:

- Search V1 requires `search_queries`; settings like `max_results`, `source_policy`, `fetch_policy`, and excerpt settings now belong under `advanced_settings`.
- Extract V1 uses `client.extract(...)`; fetch/excerpt/full-content settings are also reorganized under `advanced_settings`.

Tests should be updated to mock/assert GA methods instead of `parallel_client.beta.search` and `parallel_client.beta.extract`.

### Additional Context

Parallel has an official Search migration guide for moving from Beta to GA/V1:
https://docs.parallel.ai/search/search-migration-guide

The guide documents the relevant SDK change:

- Beta: `client.beta.search()` using `/v1beta/search`
- GA/V1: `client.search()` using `/v1/search`

It also notes that the V1 request shape changed: `search_queries` is now required, and settings such as `max_results`, `source_policy`, `fetch_policy`, and excerpt settings should be moved under `advanced_settings`.

Agno's current `ParallelTools.parallel_search()` still uses the old beta SDK path and beta-style request shape, so it breaks with `parallel-web` 1.0.x.
