### ISSUE TITLE
[Bug] CSVReader silently returns no documents for text streams: read paths call .decode() unconditionally

### ISSUE THREAD

**Issue by harbinresearcher** [agno-agi/agno#10354]
### Description

`CSVReader.read()` and `CSVReader.async_read()` call `.decode()` unconditionally on whatever the file-like object returns:

```python
# libs/agno/agno/knowledge/reader/csv_reader.py
file_content = io.StringIO(file.read().decode(self.encoding or "utf-8"))
```

When the argument is a `StringIO`, or a file handle opened in text mode, `file.read()` already returns a `str`, so the call raises `AttributeError: 'str' object has no attribute 'decode'`. That is caught by the blanket `except Exception` at the end of both methods and logged, and the reader then **returns an empty list with no signal to the caller** — the same failure mode described in #10203 for `TextReader`.

`TextReader` (#10203) and `MarkdownReader` (#10168) were both fixed to decode only byte results; `CSVReader` has the same shape in both of its read paths and was not covered.

### Steps to Reproduce

```python
import io
from agno.knowledge.reader.csv_reader import CSVReader

csv_text = "name,score\nalice,1\nbob,2\n"

CSVReader(chunk=False).read(io.StringIO(csv_text))
# observed: []  (and "Error reading <_io.StringIO ...>: 'str' object has no attribute 'decode'" in the log)

CSVReader(chunk=False).read(io.BytesIO(csv_text.encode()))
# observed: one document — bytes work, text does not
```

The same holds for a path opened in text mode:

```python
with open("sample.csv", "r", encoding="utf-8", newline="") as handle:
    CSVReader(chunk=False).read(handle)
# observed: []
```

`async_read()` behaves identically for both inputs.

### Expected Behavior

A file-like object that yields text is read the same way as one that yields bytes, so `read()` returns the documents for both `StringIO` and `BytesIO` inputs.

### Actual Behavior

Text streams silently produce no documents. Only the binary case works:

```
StringIO (text)          -> 0 documents   ("'str' object has no attribute 'decode'")
text-mode file handle    -> 0 documents
BytesIO (binary)         -> 1 document
path (str)               -> 1 document
```

### Environment

- OS: Windows 11
- Python: 3.11.16
- Agno Version: current `main` (`85b6d1d`)
- External Dependency Versions: aiofiles 25.1.0

### Possible Solutions (optional)

Decode only byte results in both paths, matching `TextReader` and `MarkdownReader`:

```python
file_contents = file.read()
if isinstance(file_contents, bytes):
    file_contents = file_contents.decode(self.encoding or "utf-8")
file_content = io.StringIO(file_contents)
```

I have this implemented with regression tests and will open a PR referencing this issue.
