### ISSUE TITLE
[Bug] CSVReader silently drops temporary file streams with non-string names

### ISSUE THREAD

**Issue by hfg369** [agno-agi/agno#10490]
## Description

`CSVReader.read()` and `CSVReader.async_read()` return an empty list for a valid CSV when the supplied file-like object's `name` is an integer or `None`. Standard-library `TemporaryFile` and unrolled `SpooledTemporaryFile` expose these shapes on macOS/Linux.

Both paths call `.split(".")` on `file.name` without checking its type. The resulting `AttributeError` is caught and valid input is silently discarded.

## Reproduction

```python
import asyncio
import tempfile
from agno.knowledge.reader.csv_reader import CSVReader

for factory in (tempfile.TemporaryFile, tempfile.SpooledTemporaryFile):
    with factory(mode="w+b") as stream:
        stream.write(b"name,age\nAlice,30\n")
        reader = CSVReader(chunk=False)
        print(factory.__name__, type(stream.name).__name__)
        print(reader.read(stream))
        print(asyncio.run(reader.async_read(stream)))
```

Observed on unmodified main `0421a1256fcc8d319144da930017fa77c5349c02`, Agno 3.0.10, macOS, Python 3.12.13: both methods return `[]`, logging `'int' object has no attribute 'split'` or `'NoneType' object has no attribute 'split'`. Explicit `name="people"` avoids the error.

Expected: valid streams are read using the existing `csv_file` fallback when no string name is available. Explicit name overrides and string-named streams should retain their current behavior.

A focused fix with sync/async, chunked/unchunked and stream-ownership regression tests is in #10489. The 11 new cases produce 10 failures and one passing compatibility control against isolated original code; both CSV test modules pass on the fix (110 tests). This issue was created to satisfy the PR triage request for an issue link.

AI disclosure: reproduced, implemented and independently checked by Codex agents acting for hfg369; no human code review is claimed.
